### ISSUE TITLE
What about Cocoapods support?

### ISSUE THREAD

**Issue by funkenstrahlen** [loopwxservices/WXKDarkSky#6]
Have you thought about this? Any special reason why you only support SPM?

**Comment by jonblatho** [comment]
The reason we’ve only supported SPM so far is WXKDarkSky is part of a broader, server-side project, so we’ve never needed anything except SPM. This project has always been something of a “here’s something we’ve worked on and it might be of use to you, too” thing.

Additionally, using CocoaPods implies (to me, at least) that you’re making Dark Sky requests from a client application, presumably on one of Apple’s four OSes (as CocoaPods doesn’t work with Linux as far as I know), which may put your API key at risk of being compromised.

We’re certainly open to adding CocoaPods support if you absolutely need it. (I’ve never done that before, though, so it’s also entirely possible that I screw it up.)

**Comment by jonblatho** [comment]
Closing this unless some folks want it in the future.
